steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - cloud-sql-function
      - --runtime=python310
      - --trigger-http
      - --no-allow-unauthenticated
      - --region=us-central1
      - --entry-point=execute_sql
      - --timeout=300
      - --memory=512MB
      - --source=.
      - --env-vars-file=env_vars.yaml
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1200s
