steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - cloud-sql-function
      - --runtime=python310
      - --trigger-http
      - --allow-unauthenticated
      - --set-env-vars=INSTANCE_CONNECTION_NAME=sanath:us-central1:konnettest3,DB_NAME=postgres,DB_USER=189614076516-compute@developer,SQL_QUERY="CREATE TABLE IF NOT EXISTS test_table (id SERIAL PRIMARY KEY, name VARCHAR(50), age INT); INSERT INTO test_table (name, age) VALUES ('John Doe', 30);"
      - --region=us-central1
      - --entry-point=execute_sql
      - --timeout=300
      - --memory=512MB
      - --source=.

timeout: 1200s

